---
- name: mkdir -p /etc/docker-registry/auth
  become: yes
  become_user: root
  file: >
    state=directory
    dest={{docker_registry_conf_dir}}/auth
    group=docker
    mode=0777
    
- name: touch /etc/docker-registry/auth/registry.htpasswd
  become: yes
  become_user: root
  file: >-
    state=touch
    path={{docker_registry_registry_htpasswd}}
    group=docker
    mode=0666

- name: build /etc/docker-registry/auth/registry.htpasswd
  become: yes
  become_user: root
  command: >
    docker run
    --rm
    --entrypoint htpasswd
    -v {{docker_registry_registry_htpasswd}}:{{docker_registry_registry_htpasswd}}
    registry:2
    -Bb {{docker_registry_registry_htpasswd}} {{item.uid}} {{item.pwd}}
  with_items: '{{docker_registry_users}}'

- name : launching registry container...
  become: yes
  become_user: root
  docker :
    state: started
    restart_policy: always
    name: registry
    image: '{{docker_registry_container}}'
    ports:
      - '{{docker_registry_https_port}}:5000'
    env:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.htpasswd
      REGISTRY_HTTP_TLS_CERTIFICATE: '/certs/{{inventory_hostname}}.pem'
      REGISTRY_HTTP_TLS_KEY: '/keys/{{inventory_hostname}}-key.pem'
      REGISTRY_HTTP_SECRET: '{{docker_registry_http_secret}}'
    volumes:
      - '{{docker_registry_dir}}/registry:/var/lib/registry'
      - /etc/docker-registry/auth:/auth
      - /etc/pki/tls/private:/keys
      - /etc/pki/tls/certs:/certs
