---
- name: mkdir -p /etc/docker-registry/auth
  file: >
    state=directory
    dest={{docker_registry_conf_dir}}/auth
    owner=root
    group=root

- name: build /etc/docker-registry/auth/nginx.conf
  template: >
    src=nginx.conf.j2
    dest={{docker_registry_conf_dir}}/auth/nginx.conf
    owner=root
    group=root
    
- name: build /etc/docker-registry/auth/nginx.htpasswd
  command: >
    docker run
    --rm
    --entrypoint htpasswd
    -v {{docker_registry_conf_dir}}/auth/nginx.htpasswd:{{docker_registry_conf_dir}}/auth/nginx.htpasswd
    httpd:2.4
    -b {{docker_registry_conf_dir}}/auth/nginx.htpasswd {{item.uid}} {{item.pwd}}
  with_items: docker_registry_users

- name : launching docker registry (backend)...
  docker :
    state: started
    restart_policy: always
    name: registry
    image: 'registry:2'
    ports:
      - '127.0.0.1:5000:5000'

- name : launching docker registry (frontend)...
  docker :
    state: started
    restart_policy: always
    name: registry-frontend
    image: 'nginx:1.9'
    ports:
      - '5043:443'
    links:
      - 'registry:registry'
    volumes:
      - /etc/pki/tls/private:/keys
      - /etc/pki/tls/certs:/certs
      - {{docker_registry_conf_dir}}/auth:/etc/nginx/conf.d
      
      
