---
- name: mkdir -p /etc/docker-registry/auth
  become: yes
  become_user: root
  with_items:
    - /etc/docker-registry
    - /etc/docker-registry/auth
  file: >
    state=directory
    dest={{item}}
    group=docker
    mode=0777
    
- name: touch /etc/docker-registry/auth/registry.htpasswd
  become: yes
  become_user: root
  file: >-
    state=touch
    path=/etc/docker-registry/auth/registry.htpasswd
    group=docker
    mode=0666

- name: build /etc/docker-registry/auth/registry.htpasswd
  become: yes
  become_user: root
  command: >
    docker run
    --rm
    --entrypoint htpasswd
    -v /etc/docker-registry/auth/registry.htpasswd:/etc/docker-registry/auth/registry.htpasswd
    registry:2
    -Bb /etc/docker-registry/auth/registry.htpasswd {{item.uid}} {{item.pwd}}
  with_items: '{{docker_registry_users}}'

- name: templatize...
  become: yes
  become_user: root
  with_items:
    - etc/docker-registry/config.yml
  template: >-
    src={{item}}.j2
    dest=/{{item}}
    mode=0644
  
- name : launching registry container...
  become: yes
  become_user: root
  docker :
    state: started
    restart_policy: always
    name: '{{docker_registry_container_name}}'
    image: '{{docker_registry_container}}'
    ports:
      - '{{docker_registry_https_port}}:5000'
    volumes:
      - '{{docker_registry_dir}}/registry:/var/lib/registry:rw'
      - /etc/docker-registry/config.yml:/etc/docker/registry/config.yml:ro
      - /etc/docker-registry/auth:/auth:ro
      - /etc/pki/tls/private:/keys:ro
      - /etc/pki/tls/certs:/certs:ro

- name: launch registry web interface
  become: yes
  become_user: root
  docker:
    state: started
    restart_policy: always
    name: '{{docker_registry_web_container_name}}'
    image: '{{docker_registry_web_container}}'
    expose: 8080
    ports:
      - '{{docker_registry_web_http_port}}:8080'
    env:
      REGISTRY_URL: https://{{docker_registry_container_name}}:5000/v2
      REGISTRY_TRUST_ANY_SSL: true
      REGISTRY_BASIC_AUTH: '{{docker_registry_web_userpwd | b64encode}}'
      REGISTRY_NAME: localhost:5000
      REGISTRY_READONLY: false
    links:
      - '{{docker_registry_container_name}}'
