---
- name: mkdir -p /etc/docker-registry/auth
  become: yes
  become_user: root
  with_items:
    - '{{docker_registry_conf_dir}}'
    - '{{docker_registry_conf_dir}}/auth'
    - '{{docker_registry_conf_dir}}/pki'
  file:
    state: directory
    dest: '{{item}}'
    mode: 0700

- include: pki.yml

- name: add passwds to /etc/docker-registry/auth/registry.htpasswd
  become: yes
  become_user: root
  with_items: '{{docker_registry_users}}'
  htpasswd:
    path: '{{docker_registry_conf_dir}}/auth/registry.htpasswd'
    mode: 0600
    name: '{{item.uid}}'
    password: '{{item.pwd}}'
    crypt_scheme: bcrypt

- name: templatize...
  become: yes
  become_user: root
  with_items:
    - config.yml
  template:
    src: '{{item}}.j2'
    dest: '{{docker_registry_conf_dir}}/{{item}}'
    mode: 0644
  
- name : launching registry container...
  become: yes
  become_user: root
  when: docker_registry_activate
  docker_container :
    state: started
    restart_policy: always
    name: '{{docker_registry_container_name}}'
    image: '{{docker_registry_container}}'
    pull: true
    published_ports:
      - '{{docker_registry_https_port}}:5000'
    volumes:
      - '{{docker_registry_dir}}/registry:/var/lib/registry:rw'
      - '{{docker_registry_conf_dir}}/config.yml:/etc/docker/registry/config.yml:ro'
      - '{{docker_registry_conf_dir}}/auth:/auth:ro'
      - '{{docker_registry_conf_dir}}/pki:/pki:ro'

- name: launch registry web interface
  become: yes
  become_user: root
  when: docker_registry_web_activate
  docker_container:
    state: started
    restart_policy: always
    name: '{{docker_registry_web_container_name}}'
    image: '{{docker_registry_web_container}}'
    pull: true
    exposed_ports: 8080
    published_ports:
      - '{{docker_registry_web_http_port}}:8080'
    env:
      REGISTRY_URL: https://{{docker_registry_container_name}}:5000/v2
      REGISTRY_TRUST_ANY_SSL: true
      REGISTRY_BASIC_AUTH: '{{docker_registry_web_userpwd | b64encode}}'
      REGISTRY_NAME: localhost:5000
      REGISTRY_READONLY: false
    links:
      - '{{docker_registry_container_name}}'
