---
- name: mkdir -p /etc/docker-registry/auth
  become: yes
  become_user: root
  with_items:
    - /etc/docker-registry
    - /etc/docker-registry/auth
  file:
    state: directory
    dest: '{{item}}'
    mode: 0700
    
- name: add passwds to /etc/docker-registry/auth/registry.htpasswd
  become: yes
  become_user: root
  with_items: '{{docker_registry_users}}'
  htpasswd:
    path: /etc/docker-registry/auth/registry.htpasswd
    mode: 0600
    name: '{{item.uid}}'
    password: '{{item.pwd}}'
    crypt_scheme: bcrypt

- name: templatize...
  become: yes
  become_user: root
  with_items:
    - etc/docker-registry/config.yml
  template:
    src: '{{item}}.j2'
    dest: /{{item}}
    mode: 0644
  
- name : launching registry container...
  become: yes
  become_user: root
  when: docker_registry_activate
  docker_container :
    state: started
    restart_policy: always
    name: '{{docker_registry_container_name}}'
    image: '{{docker_registry_container}}'
    pull: true
    published_ports:
      - '{{docker_registry_https_port}}:5000'
    volumes:
      - /etc/docker-registry/config.yml:/etc/docker/registry/config.yml:ro
      - /etc/docker-registry/auth:/auth:ro
      - /etc/pki/tls/private:/keys:ro
      - /etc/pki/tls/certs:/certs:ro

