---
- name: mkdir -p /etc/docker-registry/auth
  file: >
    state=directory
    dest={{docker_registry_conf_dir}}/auth
    owner=root
    group=root

- name: build /etc/docker-registry/auth/nginx.conf
  template: >
    src=nginx.conf.j2
    dest={{docker_registry_conf_dir}}/auth/nginx.conf
    owner=root
    group=root
    
- name: create /etc/docker-registry/auth/nginx.htpasswd
  command: >
    touch {{docker_registry_conf_dir}}/auth/nginx.htpasswd

- name: build /etc/docker-registry/auth/nginx.htpasswd
  command: >
    docker run
    --rm
    --entrypoint htpasswd
    -v {{docker_registry_conf_dir}}/auth/nginx.htpasswd:{{docker_registry_conf_dir}}/auth/nginx.htpasswd
    httpd:2.4
    -b {{docker_registry_conf_dir}}/auth/nginx.htpasswd {{item.uid}} {{item.pwd}}
  with_items: docker_registry_users

- name : check if registry volume exists
  command: docker inspect registry-volume
  register: registry_volume_exists
  failed_when: false

- name : create registry volume if it does not exist
  command: docker create -v /var/lib/registry --name registry-volume registry:2
  when: registry_volume_exists|failed

- name : launching docker registry (backend)...
  docker :
    state: started
    restart_policy: always
    name: registry
    image: 'registry:2'
    ports:
      - '127.0.0.1:5000:5000'
    volumes_from:
      - registry-volume

- name : launching docker registry (frontend)...
  docker :
    state: started
    restart_policy: always
    name: registry-frontend
    image: 'nginx:1.9'
    ports:
      - '5043:443'
    links:
      - 'registry:registry'
    volumes:
      - /etc/pki/tls/private:/keys
      - /etc/pki/tls/certs:/certs
      - '{{docker_registry_conf_dir}}/auth:/etc/nginx/conf.d'
