---
- name: mkdir -p /etc/docker-registry/auth
  file: >
    state=directory
    dest=/etc/docker-registry/auth
    owner=root
    group=root

- name: build /etc/docker-registry/auth/nginx.conf
  template: >
    src=nginx.conf.j2
    dest=/etc/docker-registry/auth/nginx.conf
    owner=root
    group=root
    
- name: build /etc/docker-registry/auth/nginx.htpasswd
  shell: docker run --rm --entrypoint htpasswd httpd:2.4 -bn arothste password > /etc/docker-registry/auth/nginx.htpasswd
  args:
    creates: /etc/docker-registry/auth/nginx.htpasswd

- name : launching docker registry (backend)...
  docker :
    state: started
    restart_policy: always
    name: registry
    image: 'registry:2'
    ports:
      - '127.0.0.1:5000:5000'

- name : launching docker registry (frontend)...
  docker :
    state: started
    restart_policy: always
    name: registry-frontend
    image: 'nginx:1.9'
    ports:
      - '5043:443'
    links:
      - 'registry:registry'
    volumes:
      - /etc/pki/tls/private:/keys
      - /etc/pki/tls/certs:/certs
      - /etc/docker-registry/auth:/etc/nginx/conf.d
      
      
