---
- name: configuring docker access for the root user...
  become: yes
  become_user: root
  with_items:
    - {f: '{{docker_registry_pki_cert_src}}', t: cert.pem, m: '0600'}
    - {f: '{{docker_registry_pki_key_src}}', t: key.pem, m: '0400'}
  copy:
    src: '{{item.f}}'
    dest: '{{docker_registry_conf_dir}}/pki/{{item.t}}'
    mode: '{{item.m}}'

